### PR TITLE
build(deps-dev): bump microbundle to 0.7.0

### PR DESCRIPTION
**Pull request by kasaharu**
Fix build error.
e.g. https://travis-ci.org/JamesHenry/ng-custom-element/jobs/558086967#L485-L487

```
$ yarn --ignore-engines
...
...
$ npm run -s build
(nodent plugin) Error: Plugin 'jsx' not found
Error: Plugin 'jsx' not found
```

I thought that microbundle build failed...
I found the issue. (https://github.com/developit/microbundle/pull/252)
And I got a solution. (https://github.com/developit/microbundle/issues/74#issuecomment-437460916)

Please check it 😃

### CODE REVIEW

**Comment by kasaharu** [comment]
Hi! @JamesHenry san.
How about this PR?
I'm glad if you check it.

**Comment by JamesHenry** [comment]
Thank you @kasaharu!

**Comment by kasaharu** [comment]
Thank you for your reviewing!

**Pull request merged**
